posts/models.py
from datetime import datetime

from sqlalchemy import Column, Integer, DateTime, ForeignKey, Text, String
from sqlalchemy.orm import relationship, backref

from ..app import db


class Comment(db.Model):
    __tablename__ = 'comments'
    id = Column(Integer, primary_key=True)
    content = Column(Text, nullable=False)
    post_id = Column(Integer, ForeignKey('posts.id'), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    parent_id = Column(Integer, ForeignKey('comments.id'), nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    replies = relationship('Comment', backref=backref('posts', remote_side=[id]))


class Post(db.Model):
    __tablename__ = 'posts'
    id = Column(Integer, primary_key=True)
    title = Column(String(128), nullable=False)
    content = Column(Text, nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    comments = relationship('Comment', backref='title', lazy='dynamic')

posts/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, HiddenField
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired


class CreatePostForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    content = TextAreaField(validators=[DataRequired()])


class CreateCommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[DataRequired()])


class CommentReplyForm(FlaskForm):
    reply = TextAreaField('Reply', validators=[DataRequired()])

posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__, url_prefix='/posts/')

from . import views

posts/views.py
from flask import render_template, request, flash, session, redirect, url_for, jsonify

from . import posts
from .models import Post, Comment
from .forms import CreatePostForm, CreateCommentForm, CommentReplyForm

from ..app import db
from ..users import User


@posts.route('/', methods=['GET', 'POST'])
def index():
    if not session.get('user_id'):
        flash('you are not login.')
        return redirect(url_for('users.login'))

    form = CreateCommentForm()
    if form.validate_on_submit():
        post_id = request.form.get('post_id')
        new_comment = Comment(content=form.comment.data, post_id=post_id, user_id=session['user_id'])
        db.session.add(new_comment)
        db.session.commit()
        flash('Your comment has been added.')
        return redirect(url_for('posts.index'))

    posts = Post.query.all()
    result = []
    for post in posts:
        comments = Comment.query.filter_by(post_id=post.id).all()
        post_data = {
            'user_id': post.user_id,
            'id': post.id,
            'username': User.query.filter(User.id == post.user_id).first().username,
            'content': post.content,
            'title': post.title,
            'timestamp': post.timestamp,
            'comments': [
                {'content': comment.content, 'username': User.query.filter(User.id == comment.user_id).first().username,
                 'timestamp': comment.timestamp} for comment in comments]
        }
        result.append(post_data)
    return render_template('posts/index.html', posts=result, form=form, current_user=True)


@posts.route('/new/', methods=['GET', 'POST'])
def create_post():
    form = CreatePostForm(request.form)
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('posts/create_post.html', form=form)

        if not session.get('user_id'):
            flash('you are not login.')
            return render_template('posts/create_post.html', form=form)

        try:
            new_post = Post()
            new_post.title = form.title.data
            new_post.content = form.content.data
            new_post.user_id = session.get('user_id')
            db.session.add(new_post)

            session['post_id'] = new_post.id
            db.session.commit()
            flash('Created Post Successfully.')
            return redirect(url_for('posts.index'))
        except:
            db.session.rollback()
            flash('Post not created!!!', 'error')
            return render_template('posts/create_post.html', form=form)

    return render_template('posts/create_post.html', form=form)


@posts.route('/posts_user/<int:post_id>', methods=['GET', 'POST'])
def posts_user(post_id):
    if not session.get('user_id'):
        flash('You are not logged in.')
        return redirect(url_for('users.login'))

    comment_form = CreateCommentForm()
    reply_form = CommentReplyForm()

    if comment_form.validate_on_submit() and 'parent_comment_id' not in request.form:
        new_comment = Comment(content=comment_form.comment.data, user_id=session['user_id'], post_id=post_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Your comment has been posted.')
        return redirect(url_for('posts.posts_user', id=post_id))

    if reply_form.validate_on_submit() and 'parent_comment_id' in request.form:
        # Replying to a comment
        reply_content = reply_form.reply.data
        parent_comment_id = request.form.get('parent_comment_id')
        new_reply = Comment(content=reply_content, user_id=session['user_id'], post_id=post_id, parent_id=parent_comment_id)
        db.session.add(new_reply)
        db.session.commit()
        flash('Your reply has been posted.')
        return redirect(url_for('posts.posts_user', post_id=post_id))

    posts = Post.query.filter(Post.user_id == post_id).all()
    result = []
    for post in posts:
        post_data = {
            'user_id': post.user_id,
            'id': post.id,
            'username': User.query.filter(User.id == post.user_id).first().username,
            'content': post.content,
            'title': post.title,
            'timestamp': post.timestamp,
            'comments': get_comments_with_replies(post.id)
        }
        result.append(post_data)
    return render_template('posts/post_user.html', posts=result, comment_form=comment_form,
                           reply_form=reply_form, current_user=True)


def get_comments_with_replies(post_id):
    comments = Comment.query.filter_by(post_id=post_id, parent_id=None).all()
    comment_tree = []
    for comment in comments:
        comment_data = {
            'content': comment.content,
            'username': User.query.filter(User.id == comment.user_id).first().username,
            'timestamp': comment.timestamp,
            'id': comment.id,
            'replies': get_replies(post_id, comment.id)
        }
        comment_tree.append(comment_data)
    return comment_tree


def get_replies(post_id, comment_id):
    replies = Comment.query.filter_by(post_id=post_id, parent_id=comment_id).all()
    print(replies)
    reply_list = []
    for reply in replies:
        reply_data = {
            'content': reply.content,
            'username': User.query.filter(User.id == reply.user_id).first().username,
            'user_id': reply.user_id,
            'timestamp': reply.timestamp,
            'id': reply.id,
            'replies': get_replies(post_id, reply.id)
        }
        reply_list.append(reply_data)
    return reply_list

templates/posts/base.html
{% extends 'base.html'%}



{% block content %}
{% include 'posts/_include/navigation.html' %}
{% block page_content %}

{% endblock %}
{% endblock %}

templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %} New Post {% endblock %}

{% block page_content %}
<h3>Create Post</h3>
<form action="{{ url_for('posts.create_post') }}" method="post">

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class=flashes>
                {% for message in messages %}
                  <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

    {{ form.hidden_tag() }}
    Title: {{ form.title }}<br/>
    Content:{{ form.content }}<br/>
    <input type="submit" value="Create">
</form>
{% endblock %}

templates/posts/index.html
{% extends 'posts/base.html'%}

{% block title %}All Posts{% endblock %}

{% block page_content %}
<hr>
<h1>All Posts</h1>
<hr>
<div>
    {% if posts %}
        {% for post in posts %}
            <div class="post">
                <h3><a href="{{ url_for('posts.posts_user', post_id=post.user_id) }}">{{ post.title }}</a></h3>
                <p>{{ post.content }}</p>
                <p><strong>Posted by:</strong> <a href="{{ url_for('posts.posts_user', post_id=post.user_id) }}">{{ post.username }}</a> on {{ post.timestamp }}</p>
                <div class="comments">
                    <h3>Comments:</h3>
                    {% if post.comments %}
                        <ul>
                            {% for comment in post.comments %}
                                <li>
                                    <p>{{ comment.content }}</p>
                                    <p><strong>Commented by:</strong> <a href="{{ url_for('posts.posts_user', post_id=post.user_id) }}">{{ comment.username }}</a> on {{ comment.timestamp }}</p>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>No comments yet.</p>
                    {% endif %}
                </div>
                <hr>
                <form method="post" action="{{ url_for('posts.index') }}">
                    {{ form.hidden_tag() }}
                    <input type="hidden" name="post_id" value="{{ post.id }}">
                    <div class="form-group">
                        {{ form.comment.label }}
                        {{ form.comment(class="form-control") }}
                    </div>
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                </form>
            </div>
        {% endfor %}

    {% else %}
        <p>No posts.</p>
    {% endif %}
</div>
{% endblock %}

templates/posts/post_user.html
{% extends 'posts/base.html'%}

{% block title %}User Posts{% endblock %}

{% block page_content %}
<hr>
<h1>User Posts</h1><br/>
<hr>
<div>
    {% for post in posts %}
        <h3>{{ post.title }}</h3>
        <h5>{{ post.username }}</h5><br/>
        <p>{{ post.content }}</p><br/><br/>
        <p>{{ post.timestamp }}</p><br/>
        <div class="comments">
            <h3>Comments:</h3>
            {% if post.comments %}
                <ul>
                    {% for comment in post.comments %}
                        <li>
                            <p>{{ comment.content }}</p>
                            <p><strong>Commented by:</strong> <a href="{{ url_for('posts.posts_user', post_id=post.user_id) }}">{{ comment.username }}</a> on {{ comment.timestamp }}</p>

                            <form method="POST" action="{{ url_for('posts.posts_user', post_id=post.id) }}">
                                {{ reply_form.hidden_tag() }}
                                {{ reply_form.reply.label }}
                                {{ reply_form.reply }}
                                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                <input type="submit" value="Submit">
                            </form>

                            <ul>
                                {% for reply in comment.replies %}
                                    <li>
                                        <p>{{ reply.content }}</p>
                                        <p><strong>Replied by:</strong> <a href="{{ url_for('posts.posts_user', post_id=reply.user_id) }}">{{ reply.username }}</a> on {{ reply.timestamp }}</p>

                                        <form method="POST" action="{{ url_for('posts.posts_user', post_id=post.id) }}">
                                            {{ reply_form.hidden_tag() }}
                                            {{ reply_form.reply.label }}
                                            {{ reply_form.reply }}
                                            <input type="hidden" name="parent_id" value="{{ reply.id }}">
                                            <input type="submit" value="Submit">
                                        </form>

                                        <ul>
                                            {% for subreply in reply.replies %}
                                                <li>
                                                    <p>{{ subreply.content }}</p>
                                                    <p><strong>Replied by:</strong> <a href="{{ url_for('posts.posts_user', post_id=subreply.user_id) }}">{{ subreply.username }}</a> on {{ subreply.timestamp }}</p>

                                                    <form method="POST" action="{{ url_for('posts.posts_user', post_id=post.id) }}">
                                                        {{ reply_form.hidden_tag() }}
                                                        {{ reply_form.reply.label }}
                                                        {{ reply_form.reply }}
                                                        <input type="hidden" name="parent_id" value="{{ subreply.id }}">
                                                        <input type="submit" value="Submit">
                                                    </form>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No comments yet.</p>
            {% endif %}

            <form method="POST" action="{{ url_for('posts.posts_user', post_id=post.id) }}">
                {{ comment_form.hidden_tag() }}
                {{ comment_form.comment.label }}
                {{ comment_form.comment }}
                <input type="hidden" name="parent_id" value="">
                <input type="submit" value="Submit">
            </form>
        </div>
        <hr>
    {% endfor %}
</div>
{% endblock %}