users/models.py
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

from ..app import db


class User(db.Model):
    __tablename__ = 'users'
    id = Column(Integer(), primary_key=True)
    username = Column(String(128), nullable=False, unique=True)
    password = Column(String(256), nullable=False)
    first_name = Column(String(30), nullable=False)
    last_name = Column(String(30), nullable=False)
    posts = relationship('Post', backref='users', lazy=True)
    comments = relationship('Comment', backref='users', lazy=True)

    def set_hash_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

users/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])


class RegisterForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    confirm_password = PasswordField(validators=[DataRequired()])
    first_name = StringField(validators=[DataRequired()])
    last_name = StringField(validators=[DataRequired()])

users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, url_prefix='/users/')

from .models import User
from .views import register, login, logout

users/views.py
from flask import request, render_template, flash, abort, session, redirect, url_for

from ..app import db
from . import users
from .forms import RegisterForm, LoginForm
from .models import User


@users.route('/')
def index():
    if not session.get('user_id'):
        flash('you are not login.')
        return redirect(url_for('users.login'))
    return render_template('users/index.html', current_user=True)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':

        if not form.validate_on_submit():
            return render_template('users/register.html', form=form)

        if not form.password.data == form.confirm_password.data:
            flash('password and confirm password must be match')
            return render_template('users/register.html', form=form)

        old_user = User.query.filter(form.username.data == User.username).first()
        if old_user:
            flash('This username is used. Must be unique.')
            return render_template('users/register.html', form=form)

        new_user = User()
        new_user.username = form.username.data
        new_user.set_hash_password(form.password.data)
        new_user.first_name = form.first_name.data
        new_user.last_name = form.last_name.data
        db.session.add(new_user)
        db.session.commit()
        flash('you are registered. successfully.')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if not form.validate_on_submit():
            abort(400)
        user = User.query.filter(User.username == form.username.data).first()
        if not user:
            flash('Incorrect username or password', category='error')
            return render_template('users/login.html', form=form)
        if not user.check_password(form.password.data):
            flash('Incorrect username or password', category='error')
            return render_template('users/login.html', form=form)

        session['username'] = user.username
        session['user_id'] = user.id
        return redirect(url_for('posts.index'))

    if session.get('username') is not None:
        return redirect(url_for('users.index'))
    return render_template('users/login.html', form=form)


@users.route('/logout/', methods=['GET'])
def logout():
    session.clear()
    flash('You are logout.')
    return redirect(url_for('users.login'))

templates/users/base.html
{% extends 'base.html'%}



{% block content %}
{% include 'users/_include/navigation.html' %}
{% block page_content %}

{% endblock %}
{% endblock %}

templates/users/index.html
{% extends 'users/base.html' %}

{% block title %} User Register {% endblock %}

{% block page_content %}
<h1>User Home Page</h1>

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %} user login {% endblock %}

{% block page_content %}
<h3>User Login</h3>
<form action="{{ url_for('users.login') }}" method="post">

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {{ form.hidden_tag() }}
    Username: {{ form.username }}<br/>
    Password:{{ form.password }}<br/>
    <input type="submit" value="Login">
</form>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %} user register {% endblock %}

{% block page_content %}
<h3>User Register</h3>
<form action="{{ url_for('users.register') }}" method="post">

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {{ form.hidden_tag() }}
    Username: {{ form.username }}<br/>
    Password:{{ form.password }}<br/>
    Confirm Password:{{ form.confirm_password }}<br/>
    FirstName:{{ form.first_name }}<br/>
    LastName:{{ form.last_name }}<br/>
    <input type="submit" value="Register">
</form>
{% endblock %}